
[pytest]
# Добавляет указанные папки в PYTHONPATH
pythonpath = .

testpaths = tests
python_files = test_*.py tests_*.py
python_functions = test_*

addopts = 
    --tb=short
    -v 
;    --alluredir=allure-results 
    --cov=src
    --cov-config=.coveragerc
    --cov-report=term-missing 
    --cov-report=html
 ;;   --clean-alluredir
